# Generated by Django 6.0.7 on 2026-08-26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

POSTGRES_CONTRACT_SQL = r"""
CREATE FUNCTION identity_check_session_family_pair()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM identity_authsession session
        JOIN identity_refreshtokenfamily family
          ON family.family_id = session.refresh_family_id
         AND family.auth_session_id = session.auth_session_id
        WHERE session.auth_session_id = NEW.auth_session_id
    ) THEN
        RAISE EXCEPTION 'AuthSession and RefreshTokenFamily must be a symmetric lifetime pair'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_session_family_pair';
    END IF;
    RETURN NULL;
END;
$$;

CREATE FUNCTION identity_check_family_session_pair()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM identity_refreshtokenfamily family
        JOIN identity_authsession session
          ON session.auth_session_id = family.auth_session_id
         AND session.refresh_family_id = family.family_id
        WHERE family.family_id = NEW.family_id
    ) THEN
        RAISE EXCEPTION 'RefreshTokenFamily and AuthSession must be a symmetric lifetime pair'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_family_session_pair';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER identity_session_family_pair_trigger
AFTER INSERT OR UPDATE ON identity_authsession
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_check_session_family_pair();

CREATE CONSTRAINT TRIGGER identity_family_session_pair_trigger
AFTER INSERT OR UPDATE ON identity_refreshtokenfamily
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION identity_check_family_session_pair();

CREATE FUNCTION identity_guard_auth_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.refresh_family_id IS NOT NULL
       AND NEW.refresh_family_id IS DISTINCT FROM OLD.refresh_family_id THEN
        RAISE EXCEPTION 'AuthSession refresh family is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_session_family_immutable';
    END IF;
    IF NEW.absolute_expires_at IS DISTINCT FROM OLD.absolute_expires_at THEN
        RAISE EXCEPTION 'AuthSession absolute expiry is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_session_expiry_immutable';
    END IF;
    IF OLD.state <> 'active' AND NEW.state IS DISTINCT FROM OLD.state THEN
        RAISE EXCEPTION 'terminal AuthSession state is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_session_terminal_immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_guard_family_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.auth_session_id IS DISTINCT FROM OLD.auth_session_id
       OR NEW.absolute_expires_at IS DISTINCT FROM OLD.absolute_expires_at THEN
        RAISE EXCEPTION 'RefreshTokenFamily lifetime identity is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_family_identity_immutable';
    END IF;
    IF OLD.state <> 'active' AND NEW.state IS DISTINCT FROM OLD.state THEN
        RAISE EXCEPTION 'terminal RefreshTokenFamily state is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_family_terminal_immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION identity_guard_credential_state()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.family_id IS DISTINCT FROM OLD.family_id
       OR NEW.generation IS DISTINCT FROM OLD.generation
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'RefreshTokenCredential lifetime identity is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_credential_identity_immutable';
    END IF;
    IF OLD.state <> 'active' AND NEW.state IS DISTINCT FROM OLD.state THEN
        RAISE EXCEPTION 'terminal RefreshTokenCredential state is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_credential_terminal_immutable';
    END IF;
    IF OLD.replaced_by_id IS NOT NULL
       AND NEW.replaced_by_id IS DISTINCT FROM OLD.replaced_by_id THEN
        RAISE EXCEPTION 'RefreshTokenCredential replacement is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'identity_credential_replacement_immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER identity_guard_auth_state_trigger
BEFORE UPDATE ON identity_authsession
FOR EACH ROW EXECUTE FUNCTION identity_guard_auth_state();

CREATE TRIGGER identity_guard_family_state_trigger
BEFORE UPDATE ON identity_refreshtokenfamily
FOR EACH ROW EXECUTE FUNCTION identity_guard_family_state();

CREATE TRIGGER identity_guard_credential_state_trigger
BEFORE UPDATE ON identity_refreshtokencredential
FOR EACH ROW EXECUTE FUNCTION identity_guard_credential_state();
"""

POSTGRES_CONTRACT_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS identity_guard_credential_state_trigger ON identity_refreshtokencredential;
DROP TRIGGER IF EXISTS identity_guard_family_state_trigger ON identity_refreshtokenfamily;
DROP TRIGGER IF EXISTS identity_guard_auth_state_trigger ON identity_authsession;
DROP TRIGGER IF EXISTS identity_family_session_pair_trigger ON identity_refreshtokenfamily;
DROP TRIGGER IF EXISTS identity_session_family_pair_trigger ON identity_authsession;
DROP FUNCTION IF EXISTS identity_guard_credential_state();
DROP FUNCTION IF EXISTS identity_guard_family_state();
DROP FUNCTION IF EXISTS identity_guard_auth_state();
DROP FUNCTION IF EXISTS identity_check_family_session_pair();
DROP FUNCTION IF EXISTS identity_check_session_family_pair();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="GameAccount",
            fields=[
                (
                    "game_account_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("instance_id", models.CharField(max_length=128)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cooling_off", "Cooling Off"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("lifecycle_version", models.PositiveBigIntegerField(default=1)),
                ("cooling_off_started_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_deadline_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "auth_session_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("logged_out", "Logged Out"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "game_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auth_sessions",
                        to="identity.gameaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCodeCredential",
            fields=[
                (
                    "recovery_code_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("code_hash", models.CharField(max_length=256)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "game_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_codes",
                        to="identity.gameaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshTokenFamily",
            fields=[
                (
                    "family_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("current_generation", models.PositiveIntegerField(default=1)),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "auth_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifetime_refresh_family",
                        to="identity.authsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshTokenCredential",
            fields=[
                (
                    "credential_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("token_hash", models.CharField(max_length=64)),
                ("jti_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="identity.refreshtokenfamily",
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaces",
                        to="identity.refreshtokencredential",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshRequestTerminalRecord",
            fields=[
                (
                    "terminal_record_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("canonical_request_hash", models.CharField(max_length=64)),
                ("access_claims_json", models.JSONField(default=dict)),
                (
                    "terminal_kind",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refresh_terminal_records",
                        to="identity.refreshtokenfamily",
                    ),
                ),
                (
                    "predecessor_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="predecessor_terminal_records",
                        to="identity.refreshtokencredential",
                    ),
                ),
                (
                    "successor_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor_terminal_records",
                        to="identity.refreshtokencredential",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authsession",
            name="refresh_family",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bound_auth_session",
                to="identity.refreshtokenfamily",
            ),
        ),
        migrations.CreateModel(
            name="SecurityAuditEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("user_id_snapshot", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "auth_session_id_snapshot",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="identity_se_event_t_1b5e1c_idx",
                    )
                ]
            },
        ),
        migrations.AddConstraint(
            model_name="gameaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "instance_id"),
                name="identity_user_instance_account_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle_version__gte", 1)),
                name="identity_account_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoverycodecredential",
            constraint=models.UniqueConstraint(
                fields=("game_account", "generation"),
                name="identity_recovery_account_generation_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoverycodecredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("game_account",),
                name="identity_recovery_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoverycodecredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1)),
                name="identity_recovery_generation_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoverycodecredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="identity_recovery_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokenfamily",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_generation__gte", 1)),
                name="identity_family_generation_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokenfamily",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="identity_family_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokencredential",
            constraint=models.UniqueConstraint(
                fields=("family", "generation"),
                name="identity_credential_family_generation_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokencredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("family",),
                name="identity_credential_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokencredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1)),
                name="identity_credential_generation_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokencredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="identity_credential_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtokencredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                name="identity_credential_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshrequestterminalrecord",
            constraint=models.UniqueConstraint(
                fields=("family", "idempotency_key"),
                name="identity_refresh_terminal_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshrequestterminalrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="identity_terminal_expiry_after_create",
            ),
        ),
        migrations.AddConstraint(
            model_name="authsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="identity_session_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="authsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("absolute_expires_at__gt", models.F("issued_at"))),
                name="identity_session_expiry_after_issue",
            ),
        ),
        migrations.RunSQL(POSTGRES_CONTRACT_SQL, POSTGRES_CONTRACT_REVERSE_SQL),
    ]
