# Generated by Django 6.0.7 on 2026-08-26 11:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_identity_immutability_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationChallenge",
            fields=[
                (
                    "challenge_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("sms", "Sms")], max_length=16),
                ),
                ("destination_lookup_digest", models.CharField(max_length=64)),
                ("destination_lookup_key_id", models.CharField(max_length=64)),
                ("code_digest", models.CharField(max_length=64)),
                ("pepper_key_id", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_delivery", "Pending Delivery"),
                            ("active", "Active"),
                            ("consumed", "Consumed"),
                            ("superseded", "Superseded"),
                            ("expired", "Expired"),
                            ("locked", "Locked"),
                            ("delivery_failed", "Delivery Failed"),
                        ],
                        default="pending_delivery",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("issued_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDeliveryOutbox",
            fields=[
                (
                    "outbox_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("template_key", models.CharField(max_length=64)),
                ("payload_ciphertext", models.TextField(blank=True, null=True)),
                ("payload_key_id", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("delivered", "Delivered"),
                            ("delivery_failed", "Delivery Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("lease_owner", models.CharField(blank=True, max_length=128, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                ("provider_category", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_outbox",
                        to="identity.verificationchallenge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationRateLimitBucket",
            fields=[
                (
                    "bucket_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("namespace", models.CharField(max_length=64)),
                ("scope", models.CharField(max_length=16)),
                ("subject_digest", models.CharField(max_length=64)),
                ("window_seconds", models.PositiveIntegerField()),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "scope", "subject_digest", "window_seconds"),
                        name="identity_verification_limit_bucket_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("window_seconds__gte", 1)),
                        name="identity_verification_limit_window_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="identity_verification_limit_version_gte_1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequestRecord",
            fields=[
                (
                    "request_record_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("canonical_request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "idempotency_key"),
                        name="identity_verification_request_key_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="identity_verification_request_retention",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerifiedContactMethod",
            fields=[
                (
                    "contact_method_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("sms", "Sms")], max_length=16),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unreachable", "Unreachable"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("destination_ciphertext", models.TextField()),
                ("encryption_key_id", models.CharField(max_length=64)),
                ("lookup_digest", models.CharField(max_length=64)),
                ("lookup_key_id", models.CharField(max_length=64)),
                ("verified_at", models.DateTimeField()),
                ("unreachable_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_contact_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("purpose", "channel", "destination_lookup_digest"),
                name="identity_challenge_one_active_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purpose", "registration"), ("user__isnull", True)),
                    models.Q(("purpose", "password_reset"), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="identity_challenge_purpose_user_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", 5)),
                name="identity_challenge_attempt_lte_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="identity_challenge_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "active"), _negated=True),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("expires_at__isnull", False),
                        ("expires_at__gt", models.F("activated_at")),
                    ),
                    _connector="OR",
                ),
                name="identity_challenge_active_window",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdeliveryoutbox",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="identity_ve_state_d6cdad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdeliveryoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="identity_delivery_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdeliveryoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("payload_ciphertext__isnull", False), ("state__in", ("pending", "leased"))
                    ),
                    models.Q(
                        ("payload_ciphertext__isnull", True),
                        ("state__in", ("delivered", "delivery_failed")),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_terminal_payload_erased",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdeliveryoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "leased"), _negated=True),
                    models.Q(("lease_owner__isnull", False), ("lease_expires_at__isnull", False)),
                    _connector="OR",
                ),
                name="identity_delivery_lease_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ("active", "unreachable"))),
                fields=("user", "channel"),
                name="identity_contact_one_usable_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedcontactmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ("active", "unreachable"))),
                fields=("channel", "lookup_digest"),
                name="identity_contact_usable_destination_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedcontactmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="identity_contact_version_gte_1"
            ),
        ),
    ]
