# Generated by Django 6.0.7 on 2026-08-26 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_verification_delivery_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state__in", ("pending_delivery", "active")), ("terminal_at__isnull", True)
                    ),
                    models.Q(
                        (
                            "state__in",
                            ("consumed", "superseded", "expired", "locked", "delivery_failed"),
                        ),
                        ("terminal_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="identity_challenge_terminal_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("state", "consumed"), _negated=True),
                        ("consumed_at__isnull", False),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(("state", "superseded"), _negated=True),
                        ("superseded_at__isnull", False),
                        _connector="OR",
                    ),
                ),
                name="identity_challenge_outcome_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdeliveryoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("delivered_at__isnull", True),
                        ("state__in", ("pending", "leased")),
                        ("terminal_at__isnull", True),
                    ),
                    models.Q(
                        ("delivered_at__isnull", False),
                        ("state", "delivered"),
                        ("terminal_at__isnull", False),
                    ),
                    models.Q(
                        ("delivered_at__isnull", True),
                        ("state", "delivery_failed"),
                        ("terminal_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="identity_delivery_state_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedcontactmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("revoked_at__isnull", True),
                        ("state", "active"),
                        ("unreachable_at__isnull", True),
                    ),
                    models.Q(
                        ("revoked_at__isnull", True),
                        ("state", "unreachable"),
                        ("unreachable_at__isnull", False),
                    ),
                    models.Q(("revoked_at__isnull", False), ("state", "revoked")),
                    _connector="OR",
                ),
                name="identity_contact_state_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedcontactmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("unreachable_at__isnull", True),
                        ("unreachable_at__gte", models.F("verified_at")),
                        _connector="OR",
                    ),
                    models.Q(
                        ("revoked_at__isnull", True),
                        ("revoked_at__gte", models.F("verified_at")),
                        _connector="OR",
                    ),
                ),
                name="identity_contact_times_after_verify",
            ),
        ),
    ]
