#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "New_Mud Linux VM 所有者确认向导"

stage "VM、Ubuntu 与中文桌面"
say "对照 plans/linux-vm-owner-runbook.md 的 O8-O12。"
step "确认 VM 是 Generation 2、6 vCPU、20 GiB 静态 RAM、240 GiB 动态 VHDX。"
step "确认 Secure Boot 使用 Microsoft UEFI CA，Default Switch，自动启动/自动检查点关闭，宿主机关机动作为 ShutDown。"
step "确认 Ubuntu 26.04 LTS Desktop、hostname=new-mud-linux、user=muddev，根文件系统是直接 ext4。"
step "确认没有 LUKS/LVM/ZFS、自动登录、Ubuntu Pro、Active Directory、Windows mount 或 SSH/RDP/SMB 服务。"
step "确认只有一个 ubuntu-installed Production checkpoint；不使用 Saved State，checkpoint 不替代备份。"
step "确认 zh_CN.UTF-8、Asia/Shanghai、Noto CJK、IBus 智能拼音、English (US) 与 Super+Space 均可用。"
step "确认自动安全更新启用、自动重启/发行版升级禁用，LC_ALL=C.UTF-8 可用于单条自动化命令。"
step "确认 Firefox 和终端已经通过中文输入验收。"
if ! confirm "上述项目是否已逐项验证，且没有挂载/共享 Windows 盘或启用远程服务？"; then
  warn "停在 Stage 1，回到 owner runbook 修正后重新运行。"
  exit 1
fi

stage "所有者管理的 VPN 与网络门禁"
say "本向导不安装、修改、诊断或记录 VPN。"
step "按 owner runbook O13 在 Ubuntu 终端运行官方站点 curl 门禁。"
step "用 Firefox 实际打开 Ubuntu、Python、GitHub、包源、VS Code Marketplace、OpenAI Codex 与 ChatGPT。"
if ! confirm "所有必需官方站点是否都能从 VM 访问，且没有把 VPN 配置交给 Codex？"; then
  warn "停在 Stage 2；请自行处理 VPN/网络，再重新运行。"
  exit 1
fi

stage "VS Code、中文界面、输入法与 Codex"
open_url "https://developers.openai.com/codex/ide/"
step "确认迁移当天的 OpenAI 官方说明仍支持 Linux VS Code IDE 扩展。"
step "确认迁移当天重新下载的 Microsoft VS Code x64 .deb 已核对 Package、Maintainer、amd64 与 SHA-256。"
step "确认中文语言包与 openai.chatgpt 已安装；Windows 旧 Codex 会话没有迁移或复用。"
step "在 VS Code 和新 Codex 输入框分别用 Super+Space/智能拼音输入中文，并让 Codex 只读回复。"
if ! confirm "Firefox、终端、VS Code、Codex 四处中文输入和 VM 内新 Codex 是否都可用？"; then
  warn "停在 Stage 3，先修复 owner runbook O14-O15 的人工步骤。"
  exit 1
fi

stage "Codex 权限模式"
say "切换和接管期间固定使用“帮我批准”。"
say "只有 L1 全部门禁通过后，日常 TDD 才可选择“完全访问权限”。"
say "完全访问仍不能影响宿主机、毁灭远端仓库或实施违法行为。"
if ! confirm "当前 Codex 是否明确处于“帮我批准”，并接受上述三条边界？"; then
  warn "停在 Stage 4，不要让 Codex执行迁移写操作。"
  exit 1
fi

stage "新仓库、remote 与最小凭据"
step "确认仓库是 public，default branch=main，origin 只指向 New_Mud_Linux。"
step "确认 Git SSH 预检后只采用一种写路径：O18 deploy key，或仅在 SSH 被阻断时采用 O18B HTTPS token。"
step "若采用 O18：deploy key 只登记在新仓库；若采用 O18B：token 只含新仓库 Contents 读写/Metadata 读取并仅在内存 cache。"
open_url "https://github.com/settings/personal-access-tokens"
step "确认独立 gh 凭据只选新仓库：Issues 读写、Actions 读取、无 Administration/Contents 写入，且不复用 Git token。"
step "确认 git push --dry-run origin main 只指向新仓库；真实 push 尚未发生。"
if ! confirm "新仓库、remote、唯一 Git 写路径与独立 gh 最小权限是否全部验证？"; then
  warn "停在 Stage 5；不要 push，也不要扩大 token 权限。"
  exit 1
fi

stage "首份异地 bundle 与恢复证据"
say "切换到 Windows 普通 PowerShell，按 owner runbook O5-O6 操作。"
step "确认 D:\\New_Mud_Backups\\bundles 有同前缀的 .bundle、.sha256、.json。"
step "确认 git fsck、git bundle verify、SHA-256 与隔离 clone 都成功。"
step "确认百度网盘中三个文件同步完成；不要向本向导输入百度凭据。"
if ! confirm "首份 bundle、验证、隔离恢复和百度副本是否全部完成？"; then
  warn "停在 Stage 6；缺失备份证据时不得 archive 旧仓库或宣布 Linux 主用。"
  exit 1
fi

stage "新 Codex 会话交接提示"
say "在 VS Code 中打开 ~/projects/New_Mud_Linux，然后新建 Codex 会话。"
say "复制下面完整提示；不要附加任何 secret："
printf '\n%s\n' \
  '这是从 Windows 到 Ubuntu Desktop VM 的 L1 迁移接管；Windows 旧 Codex 会话不能迁移或复用。先保持“帮我批准”，不要修改、暂存、提交、push、安装包或改系统配置。完整读取 AGENTS.md、plans/linux-vm-staging-migration.md、plans/linux-vm-owner-runbook.md、CONTEXT.md、docs/adr/0004 至 0008、docs/new_engine/16_OPERATIONS_TESTING_CONTRACT.md、docs/new_engine/18_IMPLEMENTATION_STATUS.md、docs/new_engine/20_AUTH_BASELINE_EVIDENCE.md 和 docs/new_engine/NEXT_SESSION_HANDOFF.md。然后只读执行 P4 审计：核对新旧仓库、main/HEAD/ahead-behind、CI、Ubuntu/硬件、直接 ext4、checkpoint、zh_CN.UTF-8、Asia/Shanghai、C.UTF-8、自动更新、输入法/四处中文输入、VS Code 扩展、文件系统挂载、SSH/RDP/SMB 和权限边界。任何 secret 只让我在本机官方界面或终端隐藏提示中输入，不得要求我粘贴到聊天。输出差异和停止条件，等我批准后先测试 Git SSH；可用时进入 O18 deploy key，被网络阻断时才进入 O18B HTTPS 回退，然后建立独立 gh 凭据并停在 P5 前。'
if ! confirm "你是否已经复制该提示，并准备在 VM 内的新 Codex 会话中粘贴？"; then
  warn "停在 Stage 7；复制完成后重新运行或从 owner runbook O17 取得同一提示。"
  exit 1
fi

finish
