# Generated by Django 6.0.7 on 2026-07-19 12:18

import uuid

import django.db.models.deletion
from django.db import migrations, models

POSTGRES_CONTRACT_SQL = r"""
ALTER TABLE content_blueprintrevision
    ADD CONSTRAINT content_revision_head_key_fk
    FOREIGN KEY (head_id, blueprint_key)
    REFERENCES content_blueprinthead (head_id, blueprint_key)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_blueprintrevision
    ADD CONSTRAINT content_revision_source_head_fk
    FOREIGN KEY (source_revision_id, head_id)
    REFERENCES content_blueprintrevision (revision_id, head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_blueprinthead
    ADD CONSTRAINT content_head_draft_revision_fk
    FOREIGN KEY (draft_revision_id, head_id)
    REFERENCES content_blueprintrevision (revision_id, head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_blueprinthead
    ADD CONSTRAINT content_head_published_revision_fk
    FOREIGN KEY (published_revision_id, head_id)
    REFERENCES content_blueprintrevision (revision_id, head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_resolvedblueprintdependency
    ADD CONSTRAINT content_dependency_target_head_key_fk
    FOREIGN KEY (target_head_id, target_blueprint_key)
    REFERENCES content_blueprinthead (head_id, blueprint_key)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_resolvedblueprintdependency
    ADD CONSTRAINT content_dependency_target_revision_fk
    FOREIGN KEY (target_revision_id, target_head_id)
    REFERENCES content_blueprintrevision (revision_id, head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_contentreleasehead
    ADD CONSTRAINT content_release_head_active_batch_fk
    FOREIGN KEY (active_batch_id, release_head_id)
    REFERENCES content_contentreleasebatch (batch_id, release_head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_contentreleasebatch
    ADD CONSTRAINT content_release_batch_parent_fk
    FOREIGN KEY (parent_batch_id, release_head_id)
    REFERENCES content_contentreleasebatch (batch_id, release_head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_contentreleaseitem
    ADD CONSTRAINT content_release_item_batch_fk
    FOREIGN KEY (batch_id, release_head_id)
    REFERENCES content_contentreleasebatch (batch_id, release_head_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_contentreleaseitem
    ADD CONSTRAINT content_release_item_head_key_fk
    FOREIGN KEY (blueprint_head_id, blueprint_key)
    REFERENCES content_blueprinthead (head_id, blueprint_key)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE content_contentreleaseitem
    ADD CONSTRAINT content_release_item_revision_head_fk
    FOREIGN KEY (published_revision_id, blueprint_head_id)
    REFERENCES content_blueprintrevision (revision_id, head_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE FUNCTION content_check_head_revision_kinds()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.draft_revision_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM content_blueprintrevision revision
        WHERE revision.revision_id = NEW.draft_revision_id
          AND revision.head_id = NEW.head_id
          AND revision.revision_kind = 'draft'
    ) THEN
        RAISE EXCEPTION 'draft revision must belong to the head and have kind draft'
            USING ERRCODE = '23514', CONSTRAINT = 'content_head_revision_kind_check';
    END IF;

    IF NEW.published_revision_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM content_blueprintrevision revision
        WHERE revision.revision_id = NEW.published_revision_id
          AND revision.head_id = NEW.head_id
          AND revision.revision_kind = 'published'
    ) THEN
        RAISE EXCEPTION 'published revision must belong to the head and have kind published'
            USING ERRCODE = '23514', CONSTRAINT = 'content_head_revision_kind_check';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER content_head_revision_kind_check
AFTER INSERT OR UPDATE ON content_blueprinthead
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION content_check_head_revision_kinds();

CREATE FUNCTION content_check_release_head_active_batch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.release_version > 0 AND NOT EXISTS (
        SELECT 1
        FROM content_contentreleasebatch batch
        WHERE batch.batch_id = NEW.active_batch_id
          AND batch.release_head_id = NEW.release_head_id
          AND batch.release_version = NEW.release_version
    ) THEN
        RAISE EXCEPTION 'active batch version must match its release head'
            USING ERRCODE = '23514', CONSTRAINT = 'content_release_head_active_batch_check';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER content_release_head_active_batch_check
AFTER INSERT OR UPDATE ON content_contentreleasehead
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION content_check_release_head_active_batch();

CREATE FUNCTION content_check_release_batch_parent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.release_version = 1 AND NEW.parent_batch_id IS NOT NULL THEN
        RAISE EXCEPTION 'the first release batch cannot have a parent'
            USING ERRCODE = '23514', CONSTRAINT = 'content_release_batch_parent_check';
    END IF;

    IF NEW.release_version > 1 AND NOT EXISTS (
        SELECT 1
        FROM content_contentreleasebatch parent
        WHERE parent.batch_id = NEW.parent_batch_id
          AND parent.release_head_id = NEW.release_head_id
          AND parent.release_version = NEW.release_version - 1
    ) THEN
        RAISE EXCEPTION 'release batch parent must be the preceding version in the same flow'
            USING ERRCODE = '23514', CONSTRAINT = 'content_release_batch_parent_check';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER content_release_batch_parent_check
AFTER INSERT OR UPDATE ON content_contentreleasebatch
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION content_check_release_batch_parent();

CREATE FUNCTION content_check_release_item_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM content_blueprintrevision revision
        WHERE revision.revision_id = NEW.published_revision_id
          AND revision.head_id = NEW.blueprint_head_id
          AND revision.revision_kind = 'published'
    ) THEN
        RAISE EXCEPTION 'release item revision must be published and belong to its blueprint head'
            USING ERRCODE = '23514', CONSTRAINT = 'content_release_item_scope_check';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM content_blueprinthead blueprint_head
        JOIN content_contentreleasehead release_head
          ON release_head.release_head_id = NEW.release_head_id
        WHERE blueprint_head.head_id = NEW.blueprint_head_id
          AND blueprint_head.instance_id = release_head.instance_id
          AND blueprint_head.mudlib_key = release_head.mudlib_key
    ) THEN
        RAISE EXCEPTION 'release item blueprint and release flow must share instance and MUDLib'
            USING ERRCODE = '23514', CONSTRAINT = 'content_release_item_scope_check';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER content_release_item_scope_check
AFTER INSERT OR UPDATE ON content_contentreleaseitem
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION content_check_release_item_scope();

CREATE FUNCTION content_check_revision_batch_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.created_in_batch_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM content_blueprinthead blueprint_head
        JOIN content_contentreleasebatch batch
          ON batch.batch_id = NEW.created_in_batch_id
        JOIN content_contentreleasehead release_head
          ON release_head.release_head_id = batch.release_head_id
        WHERE blueprint_head.head_id = NEW.head_id
          AND blueprint_head.instance_id = release_head.instance_id
          AND blueprint_head.mudlib_key = release_head.mudlib_key
    ) THEN
        RAISE EXCEPTION 'revision creation batch must share instance and MUDLib with its head'
            USING ERRCODE = '23514', CONSTRAINT = 'content_revision_batch_scope_check';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER content_revision_batch_scope_check
AFTER INSERT OR UPDATE ON content_blueprintrevision
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION content_check_revision_batch_scope();

CREATE FUNCTION content_reject_immutable_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER content_revision_immutable
BEFORE UPDATE ON content_blueprintrevision
FOR EACH ROW EXECUTE FUNCTION content_reject_immutable_update();

CREATE TRIGGER content_blueprint_dependency_immutable
BEFORE UPDATE ON content_resolvedblueprintdependency
FOR EACH ROW EXECUTE FUNCTION content_reject_immutable_update();

CREATE TRIGGER content_registry_dependency_immutable
BEFORE UPDATE ON content_resolvedregistrydependency
FOR EACH ROW EXECUTE FUNCTION content_reject_immutable_update();

CREATE TRIGGER content_release_batch_immutable
BEFORE UPDATE ON content_contentreleasebatch
FOR EACH ROW EXECUTE FUNCTION content_reject_immutable_update();

CREATE TRIGGER content_release_item_immutable
BEFORE UPDATE ON content_contentreleaseitem
FOR EACH ROW EXECUTE FUNCTION content_reject_immutable_update();
"""

POSTGRES_CONTRACT_REVERSE_SQL = r"""
DROP TRIGGER content_release_item_immutable ON content_contentreleaseitem;
DROP TRIGGER content_release_batch_immutable ON content_contentreleasebatch;
DROP TRIGGER content_registry_dependency_immutable ON content_resolvedregistrydependency;
DROP TRIGGER content_blueprint_dependency_immutable ON content_resolvedblueprintdependency;
DROP TRIGGER content_revision_immutable ON content_blueprintrevision;
DROP FUNCTION content_reject_immutable_update();

DROP TRIGGER content_revision_batch_scope_check ON content_blueprintrevision;
DROP FUNCTION content_check_revision_batch_scope();
DROP TRIGGER content_release_item_scope_check ON content_contentreleaseitem;
DROP FUNCTION content_check_release_item_scope();
DROP TRIGGER content_release_batch_parent_check ON content_contentreleasebatch;
DROP FUNCTION content_check_release_batch_parent();
DROP TRIGGER content_release_head_active_batch_check ON content_contentreleasehead;
DROP FUNCTION content_check_release_head_active_batch();
DROP TRIGGER content_head_revision_kind_check ON content_blueprinthead;
DROP FUNCTION content_check_head_revision_kinds();

ALTER TABLE content_contentreleaseitem DROP CONSTRAINT content_release_item_revision_head_fk;
ALTER TABLE content_contentreleaseitem DROP CONSTRAINT content_release_item_head_key_fk;
ALTER TABLE content_contentreleaseitem DROP CONSTRAINT content_release_item_batch_fk;
ALTER TABLE content_contentreleasebatch DROP CONSTRAINT content_release_batch_parent_fk;
ALTER TABLE content_contentreleasehead DROP CONSTRAINT content_release_head_active_batch_fk;
ALTER TABLE content_resolvedblueprintdependency
    DROP CONSTRAINT content_dependency_target_revision_fk;
ALTER TABLE content_resolvedblueprintdependency
    DROP CONSTRAINT content_dependency_target_head_key_fk;
ALTER TABLE content_blueprinthead DROP CONSTRAINT content_head_published_revision_fk;
ALTER TABLE content_blueprinthead DROP CONSTRAINT content_head_draft_revision_fk;
ALTER TABLE content_blueprintrevision DROP CONSTRAINT content_revision_source_head_fk;
ALTER TABLE content_blueprintrevision DROP CONSTRAINT content_revision_head_key_fk;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlueprintHead",
            fields=[
                (
                    "head_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_id", models.CharField(max_length=128)),
                ("mudlib_key", models.CharField(max_length=128)),
                ("blueprint_key", models.CharField(max_length=128)),
                ("edit_version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlueprintRevision",
            fields=[
                (
                    "revision_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blueprint_key", models.CharField(max_length=128)),
                (
                    "revision_kind",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        max_length=16,
                    ),
                ),
                (
                    "source_seed_bundle_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("raw_payload", models.JSONField()),
                ("compiled_payload", models.JSONField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "compiled_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "resolved_dependency_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "compiler_contract_version",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "publication_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seed_bootstrap", "Seed Bootstrap"),
                            ("content_publish", "Content Publish"),
                            ("dependency_recompile", "Dependency Recompile"),
                            ("rollback_recompile", "Rollback Recompile"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="content.blueprinthead",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_revisions",
                        to="content.blueprintrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blueprinthead",
            name="draft_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draft_for_heads",
                to="content.blueprintrevision",
            ),
        ),
        migrations.AddField(
            model_name="blueprinthead",
            name="published_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_for_heads",
                to="content.blueprintrevision",
            ),
        ),
        migrations.CreateModel(
            name="ContentReleaseBatch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("release_version", models.PositiveBigIntegerField()),
                ("manifest_version", models.CharField(max_length=32)),
                (
                    "source_seed_bundle_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("release_hash", models.CharField(max_length=64)),
                ("created_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_batches",
                        to="content.contentreleasebatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blueprintrevision",
            name="created_in_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_revisions",
                to="content.contentreleasebatch",
            ),
        ),
        migrations.CreateModel(
            name="ContentReleaseHead",
            fields=[
                (
                    "release_head_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_id", models.CharField(max_length=128)),
                ("mudlib_key", models.CharField(max_length=128)),
                ("target_content_release", models.CharField(max_length=128)),
                ("release_version", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_for_release_heads",
                        to="content.contentreleasebatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentreleasebatch",
            name="release_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="content.contentreleasehead",
            ),
        ),
        migrations.CreateModel(
            name="ContentReleaseItem",
            fields=[
                (
                    "release_item_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blueprint_key", models.CharField(max_length=128)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="content.contentreleasebatch",
                    ),
                ),
                (
                    "blueprint_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_items",
                        to="content.blueprinthead",
                    ),
                ),
                (
                    "published_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_items",
                        to="content.blueprintrevision",
                    ),
                ),
                (
                    "release_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_items",
                        to="content.contentreleasehead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResolvedBlueprintDependency",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dependency_path", models.CharField(max_length=512)),
                (
                    "dependency_kind",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("blueprint_ref", "Blueprint Ref"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("target_blueprint_key", models.CharField(max_length=128)),
                ("expected_kind", models.CharField(max_length=64)),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_dependencies",
                        to="content.blueprintrevision",
                    ),
                ),
                (
                    "target_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_blueprint_dependencies",
                        to="content.blueprinthead",
                    ),
                ),
                (
                    "target_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_revision_dependencies",
                        to="content.blueprintrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResolvedRegistryDependency",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dependency_path", models.CharField(max_length=512)),
                ("ordinal", models.PositiveIntegerField()),
                ("registry_kind", models.CharField(max_length=64)),
                ("registry_key", models.CharField(max_length=128)),
                ("registry_version", models.CharField(max_length=32)),
                ("definition_hash", models.CharField(max_length=64)),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registry_dependencies",
                        to="content.blueprintrevision",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="blueprinthead",
            constraint=models.UniqueConstraint(
                fields=("instance_id", "mudlib_key", "blueprint_key"),
                name="content_head_namespace_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprinthead",
            constraint=models.UniqueConstraint(
                fields=("head_id", "blueprint_key"), name="content_head_id_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprinthead",
            constraint=models.CheckConstraint(
                condition=models.Q(("edit_version__gte", 1)),
                name="content_head_edit_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintrevision",
            constraint=models.UniqueConstraint(
                fields=("revision_id", "head"), name="content_revision_id_head_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("compiled_hash__isnull", True),
                        ("compiled_payload__isnull", True),
                        ("compiler_contract_version__isnull", True),
                        ("created_in_batch__isnull", True),
                        ("publication_reason__isnull", True),
                        ("resolved_dependency_hash__isnull", True),
                        ("revision_kind", "draft"),
                    ),
                    models.Q(
                        ("compiled_hash__isnull", False),
                        ("compiled_payload__isnull", False),
                        ("compiler_contract_version__isnull", False),
                        ("created_in_batch__isnull", False),
                        ("publication_reason__isnull", False),
                        ("resolved_dependency_hash__isnull", False),
                        ("revision_kind", "published"),
                    ),
                    _connector="OR",
                ),
                name="content_revision_kind_fields_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleasehead",
            constraint=models.UniqueConstraint(
                fields=("instance_id", "mudlib_key", "target_content_release"),
                name="content_release_head_namespace_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleasehead",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active_batch__isnull", True), ("release_version", 0)),
                    models.Q(("active_batch__isnull", False), ("release_version__gte", 1)),
                    _connector="OR",
                ),
                name="content_release_head_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleasebatch",
            constraint=models.UniqueConstraint(
                fields=("batch_id", "release_head"), name="content_batch_id_head_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleasebatch",
            constraint=models.UniqueConstraint(
                fields=("release_head", "release_version"),
                name="content_batch_head_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleasebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("release_version__gte", 1)),
                name="content_batch_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleaseitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "blueprint_head"), name="content_item_batch_head_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreleaseitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "blueprint_key"), name="content_item_batch_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="resolvedblueprintdependency",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_revision",
                    "dependency_kind",
                    "dependency_path",
                    "ordinal",
                ),
                name="content_blueprint_dependency_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="resolvedregistrydependency",
            constraint=models.UniqueConstraint(
                fields=("source_revision", "dependency_path", "ordinal"),
                name="content_registry_dependency_uniq",
            ),
        ),
        migrations.RunSQL(
            sql=POSTGRES_CONTRACT_SQL,
            reverse_sql=POSTGRES_CONTRACT_REVERSE_SQL,
        ),
    ]
